export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'
export const SET_OPTIONS = 'SET_OPTIONS'
export const SET_SELECTED_SHOW = 'SET_SELECTED_SHOW'


export const SET_SHOW_EXTRA_DATA = 'SET_SHOW_EXTRA_DATA'

export const GET_SHOW = 'GET_SHOW'

export const SET_SELECTED_SHOW_ID = 'SET_SELECTED_SHOW_ID'
export const SET_SELECTED_SHOW_SEASONS = 'SET_SELECTED_SHOW_SEASONS'
export const SET_SELECTED_SHOW_EPISODES = 'SET_SELECTED_SHOW_EPISODES'
export const SET_SELECTED_SHOW_CAST = 'SET_SELECTED_SHOW_CAST'


